sudo: false
language: ruby
rvm:
  - 2.5.1
node_js:
  - "node"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - gem update --system
  - gem install bundler
script:
  - bin/test
