steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:builder || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--target', 'builder',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:builder',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg', 'BRANCH_NAME=$BRANCH_NAME',
    '--build-arg', 'BUILD_CONF=${_BUILD_CONF}',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:builder',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg', 'BRANCH_NAME=$BRANCH_NAME',
    '--build-arg', 'BUILD_CONF=${_BUILD_CONF}',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:builder',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    docker push us.gcr.io/$PROJECT_ID/$REPO_NAME:builder
    docker push us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA 
    # Only tag latest from master
    [ "$BRANCH_NAME" != "master" ] && exit 0
    docker tag us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA us.gcr.io/$PROJECT_ID/$REPO_NAME:latest
    docker push us.gcr.io/$PROJECT_ID/$REPO_NAME:latest
  # Deploy container image to Cloud Run for PR previews
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    # Only deploy from pull requests
    [ -z "${_PR_NUMBER}" ] && exit 0
    gcloud beta run deploy $REPO_NAME --image us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA --platform managed --region us-central1 --allow-unauthenticated --no-traffic --quiet

timeout: 1200s
